### ISSUE TITLE
Log filename when mime type parse error occurs

### ISSUE THREAD

**Issue by Uinden** [twolfson/pixelsmith#16]
I use `spritesmith` and I had JPEG file with `.png` extension and I had "fun" time investigating which one it was. Crash error does not contain any filename info.
After replacing https://github.com/twolfson/pixelsmith/blob/master/lib/engine.js#L45
```javascript
getPixels(buff, mime.lookup(file.path), cb);
```
To
```javascript
try {
    getPixels(buff, mime.lookup(file.path), cb);
} catch (e) {
    console.log('Failed to parse: ' + file.path);
    throw e;
}
```
I was able to see which file had wrong extension.
I see there is error callback call in 2 lines above
```javascript
return cb(new Error('Expected image "' + file.path + '" to not be empty but it was'));
```
So maybe somebody wants to add same for `getPixels(buff, mime.lookup(file.path), cb);`
I am not very good at this.

**Comment by twolfson** [comment]
That sounds good to me. I'm super busy then offline for the next month but
I'll get to this when I get back

**Comment by twolfson** [comment]
This has been resolved in `2.4.0`. Below is an example from our tests. Thanks for the suggestion!

```
Error: Invalid file signature (/home/todd/github/pixelsmith/test/test-files/jpeg-wrong-extension.png)
    at module.exports.Parser._parseSignature (/home/todd/github/pixelsmith/node_modules/pngjs/lib/parser.js:53:18)
    at module.exports.ChunkStream._processRead (/home/todd/github/pixelsmith/node_modules/pngjs/lib/chunkstream.js:174:13)
    at module.exports.ChunkStream._process (/home/todd/github/pixelsmith/node_modules/pngjs/lib/chunkstream.js:193:14)
    at module.exports.ChunkStream.write (/home/todd/github/pixelsmith/node_modules/pngjs/lib/chunkstream.js:61:8)
    at module.exports.ChunkStream.end (/home/todd/github/pixelsmith/node_modules/pngjs/lib/chunkstream.js:74:10)
    at exports.PNG.PNG.end (/home/todd/github/pixelsmith/node_modules/pngjs/lib/png.js:98:16)
    at exports.PNG.PNG.parse (/home/todd/github/pixelsmith/node_modules/pngjs/lib/png.js:88:8)
    at handlePNG (/home/todd/github/pixelsmith/node_modules/get-pixels/node-pixels.js:17:7)
    at doParse (/home/todd/github/pixelsmith/node_modules/get-pixels/node-pixels.js:109:7)
    at getPixels (/home/todd/github/pixelsmith/node_modules/get-pixels/node-pixels.js:140:5)
    at handleFileBuffer (/home/todd/github/pixelsmith/lib/engine.js:45:13)
    at ConcatStream.<anonymous> (/home/todd/github/pixelsmith/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:106:13)
    at ConcatStream.emit (events.js:208:7)
    at finishMaybe (/home/todd/github/pixelsmith/node_modules/readable-stream/lib/_stream_writable.js:475:14)
    at afterWrite (/home/todd/github/pixelsmith/node_modules/readable-stream/lib/_stream_writable.js:361:3)
    at _combinedTickCallback (internal/process/next_tick.js:145:20)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by Uinden** [comment]
@twolfson 
I am not sure, but I suspect
```javascript
            getPixels(buff, mime.lookup(file.path), function handleGetPixels (err, contents) {
              if (err) {
                err.message += ' (' + file.path + ')';
                cb(err);
              }
              cb(err, contents);
            });
```
Will call both `cb(err);` and `cb(err, contents);` if error occurs. So callback will be called twice.
Maybe it should be
```javascript
            getPixels(buff, mime.lookup(file.path), function handleGetPixels (err, contents) {
              if (err) {
                err.message += ' (' + file.path + ')';
                cb(err);
              } else {
                cb(err, contents);
              }
            });
```
Ignore me if I'm wrong.

**Comment by twolfson** [comment]
Ah, you're totally right. Thanks for double checking my code. I think I wrote the code in a development mindset and forgot to polish it x_x Will push a patch
